#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="youtube-dl -o \"%(title)s.%(ext)s\" --add-metadata -i" \
	yta="yt --embed-thumbnail --metadata-from-title \"%(artist)s - %(title)s\" -x --audio-format mp3 --audio-quality 0" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \

# johnstef was here
 server_plex="johnstef@plex.johnstef.com"
 server_touvlakia="johnstef@touvlakia.johnstef.com"
 server_thmmy="johnstef@thmmy-mcs.duckdns.org"
 server_johnstef="root@johnstef.com"
 server_hass="root@johnstef.duckdns.org"
 server_vasi="root@vasiplay.gr"
 alias \
   randombg="setbg ~/Files/wallpapers" \
   flutter_devtools="flutter pub global run devtools" \
   vsc='vim $(find ~/.local/bin | fzf)' \
   kad='ka Discord' \
   vifm='vifmrun' \
   vm='vifm .' \
   cfvm='vim ~/.config/vifm/vifmrc' \
   fbb='flutter pub run build_runner build --delete-conflicting-outputs' \
   fbw='flutter pub run build_runner watch --delete-conflicting-outputs' \
   phonescreen='scrcpy -m 1920' \
   owlradio="mpv https://streamer.radio.co/s3c139cbcf/listen"
